### ISSUE TITLE
自动切换

### ISSUE THREAD

**Issue by patrickk86** [vollowx/bilibili-catppuccin#1]
能否支持根据系统自动切换深浅色（Latte/Mocha），感谢！

**Comment by vollowx** [comment]
最近空闲时间不多，工作日也没法上线，不过这两天会加上这个功能的（没想到这仓库也能被发现）

**Comment by patrickk86** [comment]
好耶！好的东西值得被等待，非常感谢！

**Comment by vollowx** [comment]
和上游的模板同步了一下，现在应该可以正常使用了。
